name: rgeomod
dependencies:
  - python=3.6
  - numpy
  - conda-forge::gdal
  - clinicalgraphics::vtk
  - theano
  - jupyter
  - matplotlib
  - pandas
  - seaborn
  - scikit-image
  - pip:
    - mplstereonet
    - gempy
