dependencies:
  - python=3.6
  - numpy
  - conda-forge::gdal
  - clinicalgraphics::vtk
  - theano=1.0.1
  - jupyter
  - nb_conda
  - matplotlib
  - pandas
  - seaborn
  - scikit-image
  - tqdm
  - pip:
    - mplstereonet
    - gempy